eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8762
  
spring:
  application:
    name: eshop-product-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.56.84:3306/eshop
    username: eshop
    password: eshop
  rabbitmq:
    host: 192.168.56.100
    port: 5672
    username: rabbitadmin
    password: 123456